apiVersion: apps/v1
kind: Deployment
metadata:
  name: muhammadarif-19512-redis-deployment
  labels:
    name: redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: muhammadarif-19512-redis-pod
  template:
    metadata:
      labels:
        name: muhammadarif-19512-redis-pod
    spec:
      containers:
      - name: muhammadarif-19512-redis-container
        image: redis:latest
        ports:
        - containerPort: 6379
          hostPort: 1951
